### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by bab178** [Splitix/Hackathon2017#15]
The following are filters in our dataset:
    "_id" : String,
    "Project Name" : String,
    "Owner" : String,
    "Developer" : String,
    "Address" : String,
    "Zip Code" : Number,
    "Council District" : Number,
    "Kirwan Opportunity Index" : String,
    "Distance to Bus Stop" : String,
    "Total Units" : Number,
    "Total Affordable Units" : Number,
    "Unit Type" : String,
    "Program" : String,
    "Housing Type" : String,
    "Status" : String,
    "Affordability Start Date" : Date,
    "Affordability Period" : Number,
    "Affordability Expiration Date" : Date,
    "Certification Date" : Date,
    "C of O Date" : Date,
    "Required Amount of Fee in Lieu" : Number,
    "Date Fee in Lieu Received" : Number,
    "Units <= 30% MFI" : Number,
    "Units <= 40% MFI" : Number,
    "Units <= 50% MFI" : Number,
    "Units <= 60% MFI" : Number,
    "Units <= 65% MFI" : Number,
    "Units <= 80% MFI" : Number,
    "Units <= 100% MFI" : Number,
    "Market Rate Units" : Number,
    "City Funded Amount" : Number,
    "% of Funds Leveraged" : Number,
    "CLT" : String,
    "DDB" : String,
    "RNY" : String,
    "MDA" : String,
    "NBG" : String,
    "PUDDA" : String,
    "SMART" : String,
    "TOD" : String,
    "UNO" : String,
    "VMU" : String,
    "Location" : String

**Comment by stpCollabr8nLstn** [comment]
<img width="408" alt="screen shot 2017-04-08 at 11 04 11 am" src="https://cloud.githubusercontent.com/assets/11317322/24830405/1fe11d8c-1c4b-11e7-8b98-2b1daac2605a.png">
